name: 'GameMale Auto Sign-in'

on:
  schedule:
    - cron: '17 16 * * *' # 每天北京时间 00:17 自动运行
    - cron: '43 6 * * *'  # 每天北京时间 14:43 自动运行
  workflow_dispatch:

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ddddocr DrissionPage

      - name: Start Chrome
        run: |
          google-chrome \
            --headless=new \
            --no-sandbox \
            --disable-gpu \
            --disable-dev-shm-usage \
            --disable-software-rasterizer \
            --disable-background-networking \
            --disable-background-timer-throttling \
            --disable-renderer-backgrounding \
            --disable-features=Translate,BackForwardCache \
            --remote-debugging-address=127.0.0.1 \
            --remote-debugging-port=9222 \
            --user-data-dir=/tmp/gm-chrome \
            > /tmp/chrome.log 2>&1 &

          echo "等待 Chrome DevTools 启动..."

          for i in {1..30}; do
            if curl -s http://127.0.0.1:9222/json/version > /dev/null; then
              echo "Chrome DevTools 启动成功"
              curl -s http://127.0.0.1:9222/json/version
              break
            fi
            sleep 1
          done

          if ! curl -s http://127.0.0.1:9222/json/version > /dev/null; then
            echo "Chrome 启动失败"
            cat /tmp/chrome.log
            exit 1
          fi

      - name: Run Task Script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          CHROME_DEBUG_ADDRESS: 127.0.0.1:9222
        run: |
          python gamemale.py

      - name: Commit Asset Record
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -f gold_record.txt ]; then
            git add gold_record.txt
            git commit -m "chore: 自动更新每日金币对比基准文件" || echo "今天金币没有任何变化，跳过本次保存"
            git push
          fi

      - name: Chrome Log
        if: failure()
        run: |
          echo "===== Chrome Log ====="
          cat /tmp/chrome.log || true
